# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/one

pool:
  vmImage: ubuntu-latest

stages:
  - stage: stageA
    jobs:
      - job: jobA
        steps:
          - script: echo Hello Pooja
  - stage: stageB
    jobs:
      - job: jobB
        steps:
          - script: echo Hello


# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
